chore: remove storybook/console
```
              > korosuke613-homepage@2.0.0 build-storybook
              > storybook build --debug --disable-telemetry --output-dir /tmp/chromatic--1883-LKVzVor9K5vL --webpack-stats-json /tmp/chromatic--1883-LKVzVor9K5vL
              @storybook/cli v8.0.0
              info => Cleaning outputDir: ../../../../../tmp/chromatic--1883-LKVzVor9K5vL
              info => Loading presets
              SB_CORE-SERVER_0002 (CriticalPresetLoadError): Storybook failed to load the following preset: ./.storybook/main.ts.
              Please check whether your setup is correct, the Storybook dependencies (and their peer dependencies) are installed correctly and there are no package version clashes.
              If you believe this is a bug, please open an issue on Github.
              SB_CORE-SERVER_0002 (CriticalPresetLoadError): Storybook failed to load the following preset: ./node_modules/@storybook/addon-console/dist/index.js.
              Please check whether your setup is correct, the Storybook dependencies (and their peer dependencies) are installed correctly and there are no package version clashes.
              If you believe this is a bug, please open an issue on Github.
              Error: Cannot find module '@storybook/preview-api'
              Require stack:
              - ./node_modules/@storybook/addon-actions/dist/index.js
              - ./node_modules/@storybook/addon-console/dist/index.js
              - ./node_modules/@storybook/core-common/dist/index.js
              - ./node_modules/@storybook/telemetry/dist/index.js
              - ./node_modules/@storybook/cli/dist/generate.js
              - ./node_modules/@storybook/cli/bin/index.js
              - ./node_modules/storybook/index.js
                  at Module._resolveFilename (node:internal/modules/cjs/loader:1144:15)
                  at Module._resolveFilename (./node_modules/esbuild-register/dist/node.js:4799:36)
                  at Module._load (node:internal/modules/cjs/loader:985:27)
                  at Module.require (node:internal/modules/cjs/loader:1235:19)
                  at require (node:internal/modules/helpers:176:18)
                  at Object.<anonymous> (./node_modules/@storybook/addon-actions/dist/index.js:4:18)
                  at Module._compile (node:internal/modules/cjs/loader:1376:14)
                  at Module._extensions..js (node:internal/modules/cjs/loader:1435:10)
                  at Object.newLoader (./node_modules/esbuild-register/dist/node.js:2262:9)
                  at extensions..js (./node_modules/esbuild-register/dist/node.js:4838:24)
                  at loadPreset (./node_modules/@storybook/core-common/dist/index.js:12:59)
                  at loadPreset (./node_modules/@storybook/core-common/dist/index.js:12:59)
                  at async Promise.all (index 2)
                  at async loadPresets (./node_modules/@storybook/core-common/dist/index.js:12:483)
                  at async getPresets (./node_modules/@storybook/core-common/dist/index.js:12:1503)
                  at async buildStaticStandalone (./node_modules/@storybook/core-server/dist/index.js:24:8958)
                  at async withTelemetry (./node_modules/@storybook/core-server/dist/index.js:28:3579)
                  at async build (./node_modules/@storybook/cli/dist/generate.js:663:1409)
                  at async Command.<anonymous> (./node_modules/@storybook/cli/dist/generate.js:666:150)
10:55:45.469      → Command failed: npm run build-storybook -- --output-dir /tmp/chromatic--1883-LKVzVor9K5vL --webpack-stats-json /tmp/chromatic--1883-LKVzVor9K5vL
```